# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a941e26b431be562871f4e45a269d568998246c93f7c3929bef4536a1bc08a3b917690330bc89b74754cdf04c7da69769ff4dafc0156643f62238297e748c57

test:
  secret_key_base: 6cfb75df7811f8e2e6b4c49f93e1c003eaf2c659d6cfd2eee83ca7a69190d57e96525a89832974e0397eb972939487f9023dc26285c199f99f8d8dfcdc743af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
